---
opt_in_rules:
- anyobject_protocol
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- explicit_init
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters_brackets
- sorted_imports
- missing_docs
disabled_rules:
- line_length
- opening_brace
- multiple_closures_with_trailing_closure
- closure_end_indentation
- type_name
- multiline_parameters_brackets