# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pocketmoney_remake' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pocketmoney_remake

  target 'pocketmoney_remakeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pocketmoney_remakeUITests' do
    # Pods for testing
  end

end
